In [1]:
import numpy as np

In [2]:
a1 = np.array([[1,2,3],[1,1,1],[2,1,3]])
a2 = np.array([[2,2,2],[1,3,1],[1,2,3]])

# row = int(input("Enter the number of rows of first matrix: "))
# col = int(input("Enter the number of cols of first matrix: "))
# print("enter matrix 1 in single line seperated by space: ")
# elements1 = list(map(int, input().split()))
# matrix1 = np.array(elements1).reshape(row, col)
# print(matrix1)
# print("enter matrix 2 in single line seperated by space: ")
# elements2 = list(map(int, input().split()))
# matrix2 = np.array(elements2).reshape(row, col)
# print(matrix2)

In [3]:
print(f"Dot Product\n{np.dot(a1,a2)}")

Dot Product
[[ 7 14 13]
 [ 4  7  6]
 [ 8 13 14]]


In [4]:
print(f"Transpose of A1\n{np.transpose(a1)}")
print(f"Transpose of A2\n{np.transpose(a2)}")

Transpose of A1
[[1 1 2]
 [2 1 1]
 [3 1 3]]
Transpose of A2
[[2 1 1]
 [2 3 2]
 [2 1 3]]


In [5]:
#Trace -- Sum of diagonal elements
print(f"Trace of A1\n{np.trace(a1)}")
print(f"Trace of A2\n{np.trace(a2)}")

Trace of A1
5
Trace of A2
8


In [6]:
print(f"Rank of A1\n{np.linalg.matrix_rank(a1)}")
print(f"Rank of A2\n{np.linalg.matrix_rank(a2)}")

Rank of A1
3
Rank of A2
3


In [7]:
print(f"Det of A1\n{np.linalg.det(a1)}")
print(f"Det of A2\n{np.linalg.det(a2)}")
print(f"Inverse of A1\n{np.linalg.inv(a1)}")
print(f"Inverse of A2\n{np.linalg.inv(a2)}")
print(f"Eigen Values and Vector of A1\n{np.linalg.eig(a1)}")
print(f"Eigen Values and Vector of A2\n{np.linalg.eig(a2)}")

Det of A1
-2.9999999999999996
Det of A2
7.999999999999998
Inverse of A1
[[-0.66666667  1.          0.33333333]
 [ 0.33333333  1.         -0.66666667]
 [ 0.33333333 -1.          0.33333333]]
Inverse of A2
[[ 0.875 -0.25  -0.5  ]
 [-0.25   0.5    0.   ]
 [-0.125 -0.25   0.5  ]]
Eigen Values and Vector of A1
(array([ 5.27144292, -0.9022229 ,  0.63077998]), array([[-0.63973503, -0.88445016, -0.26674995],
       [-0.31400658,  0.26194117, -0.78642722],
       [-0.70152616,  0.38617967,  0.55711462]]))
Eigen Values and Vector of A2
(array([5.56155281, 1.        , 1.43844719]), array([[-6.19030499e-01, -8.94427191e-01,  5.24114471e-01],
       [-4.83324408e-01,  4.47213595e-01, -6.71273449e-01],
       [-6.19030499e-01, -1.12098730e-16,  5.24114471e-01]]))
