In [2]:
import numpy as np

In [2]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([5,4,3,2,1])

In [3]:
print(np.equal(a1,a2))
print(np.less(a1,a2))
print(np.less_equal(a1,a2))
print(np.greater(a1,a2))
print(np.greater_equal(a1,a2))


[False False  True False False]
[ True  True False False False]
[ True  True  True False False]
[False False False  True  True]
[False False  True  True  True]


In [4]:
a3 = np.arange(1,51,2)
print(a3)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


In [5]:
a4_identity = np.identity(3,int)
print(a4_identity)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [6]:
#Changing values - specific value range
np.random.seed(40)
a4 = np.random.randint(1,21,size=15)
print(f"Before : {a4}")
a5 = a4
a5[(a5>=10) & (a5<=15)] *= -1
print(f"After : {a5}")

Before : [ 7  8  6 19  2 13  8 19 20 11 20 10  1 18 10]
After : [  7   8   6  19   2 -13   8  19  20 -11  20 -10   1  18 -10]


In [18]:
#Changing values - specific index range
np.random.seed(40)
a4 = np.random.randint(1,21,size=15)
print(f"Before : {a4}")
a5 = a4
a5[7:12] *= -1 #Changes values of index 7 to 12
print(f"After : {a5}")

Before : [ 7  8  6 19  2 13  8 19 20 11 20 10  1 18 10]
After : [  7   8   6  19   2  13   8 -19 -20 -11 -20 -10   1  18  10]


In [7]:
#Zero Matrix and Diagonala fill
a6 = np.zeros([5,5],int) #Creates 5x5 Zero matrix (integer)
print(a6)
np.fill_diagonal(a6,[1,2,3,4,5]) #Parameters of fill_diagonal(x,y) -- x-Matrix to alter y-Values to fill 
print(a6)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [4]:
a7 = np.array([[1,1,1,1],
              [2,2,2,2],
              [3,3,3,3],
              [4,4,4,4]])
print(a7)
print(f"Column Sum : {np.sum(a7,axis=0)}")
print(f"Row Sum : {np.sum(a7,axis=1)}")
print(f"Matrix Sum : {np.sum(a7)}")


[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]]
Column Sum : [10 10 10 10]
Row Sum : [ 4  8 12 16]
Matrix Sum : 40


In [9]:
np.savetxt("Array1.txt",a7,fmt="%d")

In [8]:
# print(np.loadtxt('array.txt').astype(np.int64))
a7_copy = np.loadtxt("Array1.txt",dtype=int)
print(a7_copy)

[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]]


In [11]:
a8 = np.array([1,2,2,4])
a9 = np.array([1,2,3,4])
a10 = np.array([1,2,2,4])
print(f"A8 = A9 ? \t {np.array_equal(a8,a9)}")
print(f"A8 = A10 ? \t {np.array_equal(a8,a10)}")

A8 = A9 ? 	 False
A8 = A10 ? 	 True


In [12]:
np.random.seed(41)
a11 = np.random.randint(10,25,size=(4,4))
print(a11)
a12 = a11
a12[[0,-1],:] = a11[[-1,0],:]
# a12[[1,-1],:] = a11[[-1,1],:]
print(a12)

[[10 13 22 12]
 [10 11 13 19]
 [17 15 20 23]
 [22 18 13 13]]
[[22 18 13 13]
 [10 11 13 19]
 [17 15 20 23]
 [10 13 22 12]]


In [13]:
print(f"Sum :\n{a11+a12}")
print(f"Diff :\n{a11-a12}")
print(f"Product :\n{a11*a12}")

Sum :
[[44 36 26 26]
 [20 22 26 38]
 [34 30 40 46]
 [20 26 44 24]]
Diff :
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Product :
[[484 324 169 169]
 [100 121 169 361]
 [289 225 400 529]
 [100 169 484 144]]


In [14]:
print(np.multiply(a11,a12))

[[484 324 169 169]
 [100 121 169 361]
 [289 225 400 529]
 [100 169 484 144]]
